// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Infrastructure;

#nullable disable

namespace Movies.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220831200835_DataSeeding")]
    partial class DataSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Movies.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("date");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 9, 1, 1, 38, 35, 49, DateTimeKind.Local).AddTicks(7004),
                            Name = 0,
                            UpdatedAt = new DateTime(2022, 9, 1, 1, 38, 35, 49, DateTimeKind.Local).AddTicks(7005)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 9, 1, 1, 38, 35, 49, DateTimeKind.Local).AddTicks(7006),
                            Name = 1,
                            UpdatedAt = new DateTime(2022, 9, 1, 1, 38, 35, 49, DateTimeKind.Local).AddTicks(7007)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 9, 1, 1, 38, 35, 49, DateTimeKind.Local).AddTicks(7007),
                            Name = 2,
                            UpdatedAt = new DateTime(2022, 9, 1, 1, 38, 35, 49, DateTimeKind.Local).AddTicks(7008)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 9, 1, 1, 38, 35, 49, DateTimeKind.Local).AddTicks(7009),
                            Name = 3,
                            UpdatedAt = new DateTime(2022, 9, 1, 1, 38, 35, 49, DateTimeKind.Local).AddTicks(7009)
                        });
                });

            modelBuilder.Entity("Movies.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("date");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<int>("RuntimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 9, 1, 1, 38, 35, 49, DateTimeKind.Local).AddTicks(6983),
                            ReleaseYear = 2012,
                            RuntimeMinutes = 143,
                            Title = "Avengers",
                            UpdatedAt = new DateTime(2022, 9, 1, 1, 38, 35, 49, DateTimeKind.Local).AddTicks(6996)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 9, 1, 1, 38, 35, 49, DateTimeKind.Local).AddTicks(6998),
                            ReleaseYear = 2003,
                            RuntimeMinutes = 143,
                            Title = "Pirates of the Caribbean",
                            UpdatedAt = new DateTime(2022, 9, 1, 1, 38, 35, 49, DateTimeKind.Local).AddTicks(6998)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 9, 1, 1, 38, 35, 49, DateTimeKind.Local).AddTicks(7000),
                            ReleaseYear = 2022,
                            RuntimeMinutes = 148,
                            Title = "Spider-Man: No way home",
                            UpdatedAt = new DateTime(2022, 9, 1, 1, 38, 35, 49, DateTimeKind.Local).AddTicks(7000)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 9, 1, 1, 38, 35, 49, DateTimeKind.Local).AddTicks(7001),
                            ReleaseYear = 2021,
                            RuntimeMinutes = 148,
                            Title = "The Matrix Resurrections",
                            UpdatedAt = new DateTime(2022, 9, 1, 1, 38, 35, 49, DateTimeKind.Local).AddTicks(7001)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 9, 1, 1, 38, 35, 49, DateTimeKind.Local).AddTicks(7002),
                            ReleaseYear = 2013,
                            RuntimeMinutes = 112,
                            Title = "The Conjuring",
                            UpdatedAt = new DateTime(2022, 9, 1, 1, 38, 35, 49, DateTimeKind.Local).AddTicks(7003)
                        });
                });

            modelBuilder.Entity("Movies.Domain.Entities.MovieGenreMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieGenreMappings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreId = 2,
                            MovieId = 1
                        },
                        new
                        {
                            Id = 2,
                            GenreId = 3,
                            MovieId = 1
                        },
                        new
                        {
                            Id = 3,
                            GenreId = 1,
                            MovieId = 2
                        },
                        new
                        {
                            Id = 4,
                            GenreId = 2,
                            MovieId = 2
                        },
                        new
                        {
                            Id = 5,
                            GenreId = 3,
                            MovieId = 2
                        },
                        new
                        {
                            Id = 6,
                            GenreId = 3,
                            MovieId = 3
                        },
                        new
                        {
                            Id = 7,
                            GenreId = 2,
                            MovieId = 4
                        },
                        new
                        {
                            Id = 8,
                            GenreId = 3,
                            MovieId = 4
                        },
                        new
                        {
                            Id = 9,
                            GenreId = 3,
                            MovieId = 5
                        },
                        new
                        {
                            Id = 10,
                            GenreId = 4,
                            MovieId = 5
                        });
                });

            modelBuilder.Entity("Movies.Domain.Entities.MovieGenreMapping", b =>
                {
                    b.HasOne("Movies.Domain.Entities.Genre", null)
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movies.Domain.Entities.Movie", null)
                        .WithMany("Genres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Movies.Domain.Entities.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("Movies.Domain.Entities.Movie", b =>
                {
                    b.Navigation("Genres");
                });
#pragma warning restore 612, 618
        }
    }
}
